# Significance Weighting

In [12]:
import numpy as np
from recsys.services.io import IOService
from recsys.data.dataset import Dataset
from recsys.operator.matrix.interaction import InteractionMatrixFactory

In [2]:

FILEPATH = "tests/testdata/operators/data_operators/sampling/temporaralthreshold/ratings_random_temporal_sampling_1000.pkl"
INTERACTION ="tests/testdata/operators/weights/interaction.pkl"
USER_WEIGHTS ="tests/testdata/operators/weights/user_weights.pkl"
ITEM_WEIGHTS ="tests/testdata/operators/weights/item_weights.pkl"

## Data

In [3]:

ratings = IOService.read(FILEPATH)
ratings = Dataset(name='lab', description='Test Lab Dataset', data=ratings)

## Interaction Matrix

In [4]:
# Interaction Matrix
factory = InteractionMatrixFactory(name='lab_interaction', description='Lab Interaction Matrix', destination=INTERACTION)
I = factory.execute(data=ratings)

### User Interaction Matrix

In [5]:
csr = I.to_csr()
Iu = csr.dot(csr.T)
Iu.shape

(141779, 141779)

### User Non-Zero Entries

In [13]:
rows, cols = Iu.nonzero()
indices = np.array((rows, cols))



array([[     0,      0,      0, ..., 141778, 141778, 141778],
       [138154, 131447, 128505, ...,    146,     98,     65]], dtype=int32)

In [19]:
indices = indices.T
indices[0:10,0:2]
indices.shape

array([[     0, 138154],
       [     0, 131447],
       [     0, 128505],
       [     0, 125992],
       [     0, 120078],
       [     0, 117001],
       [     0,  87392],
       [     0,  86135],
       [     0,  71263],
       [     0,  68432]], dtype=int32)

(1476419081, 2)

In [29]:
a = csr.getcol(0).toarray()[:,0]
b = csr.getrow(71263).toarray()[0,:]
a
b
np.dot(a,b)

array([0, 0, 0, ..., 0, 0, 0])

array([0, 0, 0, ..., 0, 0, 0])

ValueError: shapes (141779,) and (47171,) not aligned: 141779 (dim 0) != 47171 (dim 0)